import { AgencyConfig } from "../../../types/agency"
import { createExportFolder, validAwsKey } from "../../../utils/file"
import { gmvUpdates } from "./updates"

export const allAgencies: {
  agency_id: number
  agency_name: string
  agency_url: string | null
  gtfs_static: string
  gtfs_rt_vehicle_positions: string
  gtfs_rt_trip_updates: string
  gtfs_rt_alerts: string
}[] = [
  {
    agency_id: 203,
    agency_name: "Beach Cities Transit",
    agency_url: "https://www.redondo.org/depts/recreation/transit/beach_cities_transit/default.asp",
    gtfs_static: "https://redondobeachBCT.com/gtfs",
    gtfs_rt_vehicle_positions: "https://redondobeachBCT.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://redondobeachBCT.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://redondobeachBCT.com/gtfs-rt/alerts",
  },
  {
    agency_id: 121,
    agency_name: "Burbank Bus",
    agency_url: "http://www.burbankbus.org/",
    gtfs_static: "https://rideburbankbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://rideburbankbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://rideburbankbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://rideburbankbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 153,
    agency_name: "Camarillo Area Transit",
    agency_url: "https://www.cityofcamarillo.org/residents/public_transportation/camarillo_area_transit.php",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 51,
    agency_name: "Capital Area Transit",
    agency_url: "https://www.cattransit.com/",
    gtfs_static: "https://findmycatbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://findmycatbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://findmycatbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://findmycatbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 151,
    agency_name: "Cities Area Transit - Grand Forks",
    agency_url: "https://CATprowler.org",
    gtfs_static: "https://CATprowler.org/gtfs",
    gtfs_rt_vehicle_positions: "https://CATprowler.org/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://CATprowler.org/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://CATprowler.org/gtfs-rt/alerts",
  },
  {
    agency_id: 71,
    agency_name: "City Of Commerce",
    agency_url: "https://www.ci.commerce.ca.us/index.aspx?NID=90",
    gtfs_static: "https://citycommbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://citycommbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://citycommbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://citycommbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 98,
    agency_name: "City of Iowa City",
    agency_url: "https://www.icgov.org/city-government/departments-and-divisions/transit",
    gtfs_static: "https://iowa.syncromatics.com/gtfs",
    gtfs_rt_vehicle_positions: "https://iowa.syncromatics.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://iowa.syncromatics.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://iowa.syncromatics.com/gtfs-rt/alerts",
  },
  {
    agency_id: 20,
    agency_name: "City of Key West",
    agency_url: "https://www.cityofkeywest-fl.gov/department/division.php?structureid=158",
    gtfs_static: "https://kwtransit.com/gtfs",
    gtfs_rt_vehicle_positions: "https://kwtransit.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://kwtransit.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://kwtransit.com/gtfs-rt/alerts",
  },
  {
    agency_id: 201,
    agency_name: "City of Norman",
    agency_url: "https://www.embarkok.com/norman",
    gtfs_static: "https://embarknorman.com/gtfs",
    gtfs_rt_vehicle_positions: "https://embarknorman.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://embarknorman.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://embarknorman.com/gtfs-rt/alerts",
  },
  {
    agency_id: 167,
    agency_name: "ColumBUS Transit",
    agency_url: "https://www.columbus.in.gov/columbus-transit/",
    gtfs_static: "https://columbusindianatransit.com/gtfs",
    gtfs_rt_vehicle_positions: "https://columbusindianatransit.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://columbusindianatransit.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://columbusindianatransit.com/gtfs-rt/alerts",
  },
  {
    agency_id: 80,
    agency_name: "Connect Transit",
    agency_url: "https://www.connect-transit.com",
    gtfs_static: "https://rideconnecttransit.com/gtfs",
    gtfs_rt_vehicle_positions: "https://rideconnecttransit.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://rideconnecttransit.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://rideconnecttransit.com/gtfs-rt/alerts",
  },
  {
    agency_id: 96,
    agency_name: "Coralville Transit",
    agency_url: "https://www.coralville.org/80/Transit-Parking",
    gtfs_static: "https://iowa.syncromatics.com/gtfs",
    gtfs_rt_vehicle_positions: "https://iowa.syncromatics.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://iowa.syncromatics.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://iowa.syncromatics.com/gtfs-rt/alerts",
  },
  {
    agency_id: 226,
    agency_name: "CVTD Cache Valley Transit District",
    agency_url: "https://cvtdbus.org",
    gtfs_static: "https://mycvtdbus.org/gtfs",
    gtfs_rt_vehicle_positions: "https://mycvtdbus.org/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://mycvtdbus.org/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://mycvtdbus.org/gtfs-rt/alerts",
  },
  {
    agency_id: 233,
    agency_name: "DAVIDSON COUNTY TRANSPORTATION SERVICES",
    agency_url: "https://www.co.davidson.nc.us/258/Transportation",
    gtfs_static: "https://dcridestracker.com/gtfs",
    gtfs_rt_vehicle_positions: "https://dcridestracker.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://dcridestracker.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://dcridestracker.com/gtfs-rt/alerts",
  },
  {
    agency_id: 100,
    agency_name: "Elk Grove Transit",
    agency_url: "https://elkgrovetransit.com/",
    gtfs_static: "https://elkgrovetransit.com/gtfs",
    gtfs_rt_vehicle_positions: "https://elkgrovetransit.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://elkgrovetransit.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://elkgrovetransit.com/gtfs-rt/alerts",
  },
  {
    agency_id: 86,
    agency_name: "Emery-Go-Round ",
    agency_url: "https://www.emerygoround.com/",
    gtfs_static: "https://egrshuttle.com/gtfs",
    gtfs_rt_vehicle_positions: "https://egrshuttle.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://egrshuttle.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://egrshuttle.com/gtfs-rt/alerts",
  },
  {
    agency_id: 139,
    agency_name: "Gold Coast Transit District",
    agency_url: "http://www.goldcoasttransit.org/",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 73,
    agency_name: "Greenlink Transit",
    agency_url: "http://ridegreenlink.com/",
    gtfs_static: "https://trackgreenlink.com/gtfs",
    gtfs_rt_vehicle_positions: "https://trackgreenlink.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://trackgreenlink.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://trackgreenlink.com/gtfs-rt/alerts",
  },
  {
    agency_id: 232,
    agency_name: "Greensboro Transit Agency",
    agency_url: "https://www.greensboro-nc.gov/index.aspx?page=2180",
    gtfs_static: "https://trackmygta.com/gtfs",
    gtfs_rt_vehicle_positions: "https://trackmygta.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://trackmygta.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://trackmygta.com/gtfs-rt/alerts",
  },
  {
    agency_id: 225,
    agency_name: "HELE-ON BUS",
    agency_url: "https://heleonbus.org",
    gtfs_static: "https://myheleonbus.org/gtfs",
    gtfs_rt_vehicle_positions: "https://myheleonbus.org/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://myheleonbus.org/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://myheleonbus.org/gtfs-rt/alerts",
  },
  {
    agency_id: 144,
    agency_name: "Kanan Shuttle",
    agency_url: "https://www.toaks.org/departments/public-works/transit/kanan-shuttle",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 224,
    agency_name: "Knoxville Area Transit",
    agency_url: "https://www.katbus.com/",
    gtfs_static: "https://knoxville.syncromatics.com/gtfs",
    gtfs_rt_vehicle_positions: "https://knoxville.syncromatics.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://knoxville.syncromatics.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://knoxville.syncromatics.com/gtfs-rt/alerts",
  },
  {
    agency_id: 44,
    agency_name: "LADOT",
    agency_url: "https://www.ladottransit.com",
    gtfs_static: "https://ladotbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://ladotbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ladotbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ladotbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 183,
    agency_name: "LADOT",
    agency_url: "https://www.ladottransit.com",
    gtfs_static: "https://ladotbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://ladotbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ladotbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ladotbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 30,
    agency_name: "LADOT",
    agency_url: "https://www.ladottransit.com",
    gtfs_static: "https://ladotbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://ladotbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ladotbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ladotbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 47,
    agency_name: "LADOT",
    agency_url: "https://www.ladottransit.com",
    gtfs_static: "https://ladotbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://ladotbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ladotbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ladotbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 45,
    agency_name: "LADOT",
    agency_url: "https://www.ladottransit.com",
    gtfs_static: "https://ladotbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://ladotbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ladotbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ladotbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 68,
    agency_name: "LaFayette Transit System",
    agency_url: "https://www.ridelts.com",
    gtfs_static: "https://lts.syncromatics.com/gtfs",
    gtfs_rt_vehicle_positions: "https://lts.syncromatics.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://lts.syncromatics.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://lts.syncromatics.com/gtfs-rt/alerts",
  },
  {
    agency_id: 227,
    agency_name: "LINK TRANSIT",
    agency_url: "https://www.linktransit.org/",
    gtfs_static: "https://mylinktransit.org/gtfs",
    gtfs_rt_vehicle_positions: "https://mylinktransit.org/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://mylinktransit.org/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://mylinktransit.org/gtfs-rt/alerts",
  },
  {
    agency_id: 33,
    agency_name: "Marin Transit",
    agency_url: "https://marintransit.org",
    gtfs_static: "https://marintransit.net/gtfs",
    gtfs_rt_vehicle_positions: "https://marintransit.net/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://marintransit.net/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://marintransit.net/gtfs-rt/alerts",
  },
  {
    agency_id: 104,
    agency_name: "Maui County Transit",
    agency_url: "https://www.mauicounty.gov/125/Department-of-Transportation",
    gtfs_static: "https://mauibus.org/gtfs",
    gtfs_rt_vehicle_positions: "https://mauibus.org/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://mauibus.org/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://mauibus.org/gtfs-rt/alerts",
  },
  {
    agency_id: 207,
    agency_name: "METRA",
    agency_url: "https://www.columbusga.gov/metra",
    gtfs_static: "https://metracolumbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://metracolumbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://metracolumbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://metracolumbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 147,
    agency_name: "Moorpark City Transit",
    agency_url: "https://www.moorparkca.gov/227/Bus-Ride-Guide",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 156,
    agency_name: "MVgo - Mountain View",
    agency_url: "https://www.mvgo.org",
    gtfs_static: "https://ridemvgo.org/gtfs",
    gtfs_rt_vehicle_positions: "https://ridemvgo.org/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ridemvgo.org/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ridemvgo.org/gtfs-rt/alerts",
  },
  {
    agency_id: 223,
    agency_name: "NAPA",
    agency_url: "https://vinetransit.com/",
    gtfs_static: "https://napa.syncromatics.com/gtfs",
    gtfs_rt_vehicle_positions: "https://napa.syncromatics.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://napa.syncromatics.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://napa.syncromatics.com/gtfs-rt/alerts",
  },
  {
    agency_id: 148,
    agency_name: "Ojai Trolley",
    agency_url: "https://ojaitrolley.com/",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 155,
    agency_name: "Palmetto Breeze Transit",
    agency_url: "https://palmettobreezetransit.com/",
    gtfs_static: "https://trackthebreeze.com/gtfs",
    gtfs_rt_vehicle_positions: "https://trackthebreeze.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://trackthebreeze.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://trackthebreeze.com/gtfs-rt/alerts",
  },
  {
    agency_id: 162,
    agency_name: "Pee Dee Regional Transportation Authority",
    agency_url: "https://www.pdrta.org/",
    gtfs_static: "https://whereispdrta.com/gtfs",
    gtfs_rt_vehicle_positions: "https://whereispdrta.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://whereispdrta.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://whereispdrta.com/gtfs-rt/alerts",
  },
  {
    agency_id: 230,
    agency_name: "Piedmont Authority for Regional Transportation",
    agency_url: "https://www.partnc.org/",
    gtfs_static: "https://partbustracker.com/gtfs",
    gtfs_rt_vehicle_positions: "https://partbustracker.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://partbustracker.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://partbustracker.com/gtfs-rt/alerts",
  },
  {
    agency_id: 18,
    agency_name: "PresidiGo",
    agency_url: "https://www.presidio.gov/transportation/presidigo",
    gtfs_static: "https://presidiobus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://presidiobus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://presidiobus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://presidiobus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 113,
    agency_name: "Pullman Transit",
    agency_url: "https://pullman-wa.gov/cms/one.aspx?pageId=16059091",
    gtfs_static: "https://pullmanbusbeacon.com/gtfs",
    gtfs_rt_vehicle_positions: "https://pullmanbusbeacon.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://pullmanbusbeacon.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://pullmanbusbeacon.com/gtfs-rt/alerts",
  },
  {
    agency_id: 235,
    agency_name: "PVVTA",
    agency_url: null,
    gtfs_static: "https://ridepvvta.com/gtfs",
    gtfs_rt_vehicle_positions: "https://ridepvvta.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ridepvvta.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ridepvvta.com/gtfs-rt/alerts",
  },
  {
    agency_id: 159,
    agency_name: "Santee Wateree RTA",
    agency_url: "https://www.swrta.com/",
    gtfs_static: "https://santeebus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://santeebus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://santeebus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://santeebus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 58,
    agency_name: "Shreveport and Bossier City, Louisiana",
    agency_url: "https://www.sportran.org",
    gtfs_static: "https://sportranbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://sportranbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://sportranbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://sportranbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 152,
    agency_name: "Simi Valley Transit",
    agency_url: "https://www.simivalley.org/departments/community-services/simi-valley-transit",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 214,
    agency_name: "SMART",
    agency_url: "https://www.ridesmart.com",
    gtfs_static: "https://mysmartbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://mysmartbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://mysmartbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://mysmartbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 211,
    agency_name: "The Kauai Bus",
    agency_url: "https://www.kauai.gov/transportation",
    gtfs_static: "https://thekauaibus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://thekauaibus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://thekauaibus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://thekauaibus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 142,
    agency_name: "Thousand Oaks Transit",
    agency_url: "https://www.toaks.org/departments/public-works/transit",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 90,
    agency_name: "Town of Vail",
    agency_url: "https://www.vailgov.com/bus-schedules",
    gtfs_static: "https://ride.vailgov.com/gtfs",
    gtfs_rt_vehicle_positions: "https://ride.vailgov.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ride.vailgov.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ride.vailgov.com/gtfs-rt/alerts",
  },
  {
    agency_id: 81,
    agency_name: "Towson University",
    agency_url: "https://www.towson.edu/parking/shuttle/",
    gtfs_static: "https://tutigerride.com/gtfs",
    gtfs_rt_vehicle_positions: "https://tutigerride.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://tutigerride.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://tutigerride.com/gtfs-rt/alerts",
  },
  {
    agency_id: 166,
    agency_name: "Tulare InterModal Express",
    agency_url: "https://tularetransit.com",
    gtfs_static: "https://tularetransit.com/gtfs",
    gtfs_rt_vehicle_positions: "https://tularetransit.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://tularetransit.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://tularetransit.com/gtfs-rt/alerts",
  },
  {
    agency_id: 146,
    agency_name: "Union City Transit",
    agency_url: "https://www.uctransit.org",
    gtfs_static: "https://uctransit.info/gtfs",
    gtfs_rt_vehicle_positions: "https://uctransit.info/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://uctransit.info/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://uctransit.info/gtfs-rt/alerts",
  },
  {
    agency_id: 97,
    agency_name: "University of Iowa - CAMBUS",
    agency_url: "https://transportation.uiowa.edu/cambus",
    gtfs_static: "https://iowa.syncromatics.com/gtfs",
    gtfs_rt_vehicle_positions: "https://iowa.syncromatics.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://iowa.syncromatics.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://iowa.syncromatics.com/gtfs-rt/alerts",
  },
  {
    agency_id: 149,
    agency_name: "Valley Express Transit Service",
    agency_url: "http://www.valleyexpressbus.org/",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 163,
    agency_name: "Valley Metro Roanoke",
    agency_url: "https://valleymetro.com/",
    gtfs_static: "https://vmgoapp.com/gtfs",
    gtfs_rt_vehicle_positions: "https://vmgoapp.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://vmgoapp.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://vmgoapp.com/gtfs-rt/alerts",
  },
  {
    agency_id: 143,
    agency_name: "VCTC Intercity",
    agency_url: "https://www.goventura.org/",
    gtfs_static: "https://govcbus.com/gtfs",
    gtfs_rt_vehicle_positions: "https://govcbus.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://govcbus.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://govcbus.com/gtfs-rt/alerts",
  },
  {
    agency_id: 112,
    agency_name: "Victor Valley Transit Authority",
    agency_url: "http://vvta.org/",
    gtfs_static: "https://ontime.vvta.org/gtfs",
    gtfs_rt_vehicle_positions: "https://ontime.vvta.org/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://ontime.vvta.org/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://ontime.vvta.org/gtfs-rt/alerts",
  },
  {
    agency_id: 84,
    agency_name: "Visalia Transit",
    agency_url: "https://www.visalia.city/depts/general_services/transit/default.asp",
    gtfs_static: "https://visaliatransit.info/gtfs",
    gtfs_rt_vehicle_positions: "https://visaliatransit.info/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://visaliatransit.info/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://visaliatransit.info/gtfs-rt/alerts",
  },
  {
    agency_id: 220,
    agency_name: "Waukesha Metro",
    agency_url: "https://waukesha-wi.gov/631/Transit",
    gtfs_static: "https://mywaukeshametro.com/gtfs",
    gtfs_rt_vehicle_positions: "https://mywaukeshametro.com/gtfs-rt/vehiclepositions",
    gtfs_rt_trip_updates: "https://mywaukeshametro.com/gtfs-rt/tripupdates",
    gtfs_rt_alerts: "https://mywaukeshametro.com/gtfs-rt/alerts",
  },
]

// timezone string lookup -
// https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

// ! ADD SUPLIMENTAL INFORMATION TO AHEAR TO AgencyConfig type

const includedAgencies: {
  agency_id: number
  agency_name: string
  timezone: string
}[] = [
  {
    agency_id: 153,
    agency_name: "Camarillo Area Transit",
    timezone: "America/New_York",
  },
  // { // ! missing stops???
  // 	agency_id: 151,
  // 	agency_name: 'Cities Area Transit',
  // 	timezone: 'America/Chicago',
  // },
  {
    agency_id: 71,
    agency_name: "City Of Commerce",
    timezone: "America/Los_Angeles",
  },
  {
    agency_id: 98,
    agency_name: "City of Iowa City",
    timezone: "America/Chicago",
  },
  {
    agency_id: 201,
    agency_name: "City of Norman",
    timezone: "America/Chicago",
  },
  {
    agency_id: 230,
    agency_name: "Piedmont Authority for Regional Transportation",
    timezone: "America/New_York",
  },
  {
    agency_id: 167,
    agency_name: "ColumBUS",
    timezone: "America/Chicago",
  },
  {
    agency_id: 80,
    agency_name: "Connect",
    timezone: "America/Chicago",
  },
]


// ! IDS are a concat of the agnecy.id and agency.name with all spaces replaced with "_" all lowercase
// ! 80_connect, 230_piedmont_authority_for_regional_transportation, 71_city_of_commerce
export const gmvAgencies = async () => {
  const updated: AgencyConfig[] = []
  for (const agency of includedAgencies) {
    const match = allAgencies.find((ag) => ag.agency_id === agency.agency_id)

    if (match) {
      // await createExportFolder(`${match.agency_id}_${match.agency_name.replaceAll(" ", "_").toLocaleLowerCase()}`)
      const _agencyConfig = {
        id: `${match.agency_id}_${match.agency_name.replaceAll(" ", "_").toLocaleLowerCase()}`,
        name: match.agency_name,
        url: match.gtfs_static,
        tripUpdates: match.gtfs_rt_trip_updates,
        vehicleUpdates: match.gtfs_rt_vehicle_positions,
        alertUpdates: match.gtfs_rt_alerts,
        updates: gmvUpdates,
        excludeList: [],
        exclude: ["directions"],
        ...agency,
      }
      updated.push(_agencyConfig)
    }
  }
  return updated
}
